// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdql8H6y473k_I2mjPRu8bC1NC6yYnagA',
    appId: '1:179162495514:web:c6740937dcd38358a3efa3',
    messagingSenderId: '179162495514',
    projectId: 'cmsc-23-todo-app-iggesmundo',
    authDomain: 'cmsc-23-todo-app-iggesmundo.firebaseapp.com',
    storageBucket: 'cmsc-23-todo-app-iggesmundo.appspot.com',
    measurementId: 'G-RGT0KKNCGF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUBzGVqWbSkpo7leiEaiohSrWEo3FVvMA',
    appId: '1:179162495514:android:310085d75fb9ab61a3efa3',
    messagingSenderId: '179162495514',
    projectId: 'cmsc-23-todo-app-iggesmundo',
    storageBucket: 'cmsc-23-todo-app-iggesmundo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPJ7oxk5zH8bZuD0HpiptfIejQgfl0TqA',
    appId: '1:179162495514:ios:6b5c22be854a1762a3efa3',
    messagingSenderId: '179162495514',
    projectId: 'cmsc-23-todo-app-iggesmundo',
    storageBucket: 'cmsc-23-todo-app-iggesmundo.appspot.com',
    iosClientId: '179162495514-ehhknloh89slafuei9hg9uh1uhcpa111.apps.googleusercontent.com',
    iosBundleId: 'com.example.week7NetworkingDiscussion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPJ7oxk5zH8bZuD0HpiptfIejQgfl0TqA',
    appId: '1:179162495514:ios:6b5c22be854a1762a3efa3',
    messagingSenderId: '179162495514',
    projectId: 'cmsc-23-todo-app-iggesmundo',
    storageBucket: 'cmsc-23-todo-app-iggesmundo.appspot.com',
    iosClientId: '179162495514-ehhknloh89slafuei9hg9uh1uhcpa111.apps.googleusercontent.com',
    iosBundleId: 'com.example.week7NetworkingDiscussion',
  );
}
